### ISSUE TITLE
I2C bit rate settings

### ISSUE THREAD

**Issue by kowalski100** [polarfire-soc/polarfire-soc-bare-metal-library#17] opened 2021-09-07 04:43 UTC
Hi, 

I am looking on setting bit rate of I2C driver. I don't see any bit rate settings except I2C0_CTRL register as shown in figure below (highlighted).

![tmp](https://user-images.githubusercontent.com/7781522/132285446-1488cb09-6a6d-40e5-b652-fa422b0616af.PNG)

1. Suppose I want bit rate of 100kb/sec (the standard i2c bit rate) and input clock frequency is 150Mhz, what will be my settings?
2. I don't see any settings to configure I2C as MASTER or Slave?

**Comment by nitindeshpande** [comment] 2021-09-08 09:12
Hi,
 1) You will unfortunately not be able to achieve exact 100KB/sec with 150Mhz. The closest you will be able to get is by choosing '100', that is devisor value of 960. 
     I am not sure about the value '111' though, because I am not sure what is the source of BCLK. I will get back to you as soon as I get to know.

2) There is no explicit 'master mode' / 'slave mode' setting via registers.
    The Core infers the mode via from its present state and the combination of ENS1, STA and AA bit values. The MSS I2C driver handles it for you.

Hope that helps.

**Comment by Keval-Joshi** [comment] 2021-09-09 05:45
Hello, 

The required registers information has been provided via the support channel. and the register map description will be updated in due time. 

Thanks.

**Comment by nitindeshpande** [comment] 2021-10-07 04:14
Required information is provided and the issue is raised with the documentation team to update the register map. Closing the issue here.

**Closed as completed by nitindeshpande** 2021-10-07 04:14 UTC
